apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Icsx3AluW/SyyTaowt0YJkE=,iv:W7q144RKlikmx9+uRLuZFWUKCwW/+tJo90y/juGsa88=,tag:Yf1heqrnU/+n7BGHTDro4w==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:DQLBnRLU+izXKxYWQptMrjO3Tu0pNkYPOXkXw2niyMBgegbNZA==,iv:ek7a1LD/8bVUNkz7l+y3nsfCli/ZUJnQ+48qGMLljz4=,tag:OaYf6C85maVOSOgg+mqUuA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:OELmXHBEtjC43RLgltRKtJ6/M7QO,iv:UW1xg1fJNDRS+7ByAzTrQkmsRMPfSWcT68B5yLudH3w=,tag:SdfsVdE0sc3wZmOuspeoWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13hgue64xevk8x27umhxz7kyjectc52hrrx8p7kfyanlsmqsxjstskek2va
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDTEpqM29sTzZHQ211WHFp
            TlhJU0k5Wk5mSGZvZXN6dzE0bXlQWWpOUkVVCkc0U1lxeFpnMWREU29SU0hpSUsz
            Q0o0WC9rVmRMZkVrOVdhelMrVlFUMncKLS0tIFh1SW1mYUlod3IzK2tpWEQ0SXgv
            dkZJODE4RGRpdzdiUzNIR085cloyMDgKEF4ImArLNU7WvVQjJ4EiVaJbgaSxIS/e
            j51WsM6O49fmnR0CKc11fOpeNBh2M6bXl/Sf5Z2/CryewkSRFCkDnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-03T20:33:30Z"
    mac: ENC[AES256_GCM,data:fpwQ2n2eoRVnn6HPnaVYwI6TWdWPiFooWomRo+c457DdL7kg6uXhaKMdS0Wxf8H/9ZQA1X8vg/Q7mC8MiujsOHv5GR5LVUHm/gHuuX0F0A4KTs0zN0MB9gUQWvUOgbpgo1TMJh4D/6ypO54nNu+16uQtNhpzhcuU21J+tHSoUHE=,iv:F3MAFdHJtXN/F5uRvo/8jh1uo4/Tydxjyiiv/WtqCiE=,tag:XIbzRE+/tTm4yzjZfKtfpw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
