apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:GD+s6VvBhk3Nw1a/bvv2s/E=,iv:UtSfMnGjGem+wcWpSS9CcQIhlLjqunfrxzRMXg98mzg=,tag:EHgM9g/wLA1n3sv9Tfoblg==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:vi4rIKLp1g0/8fRH6p6fKTcErf8p7zxHZKPYp2z3LjXM0kohXw==,iv:Y+lTblyRVZEYOM3CvlAdloyUhOvnYEkkG/51tSXfc0c=,tag:dcKIDXC687jaPLp5j7+JYw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:eos33SU8ywkOPNGq+1rqDLxq2HKB,iv:9CoCV/nzWY8wnc+YJJF9XmBzsg0Lg0aizBygqcNkGzw=,tag:VYbsVryjt716kv8VdAHaJg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13hgue64xevk8x27umhxz7kyjectc52hrrx8p7kfyanlsmqsxjstskek2va
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNGJTS3NYVGRvRU9HMG5n
            dEpOZlR6YzdJUk9tUUd1MFBxUzdIYVd5VWtnCnlyb0Y4NTh2KzFzYUVWZ3hSd3dG
            SmZGZlhaanFDN09PcUR0WHhXQ25WNHcKLS0tIFVCTFBoaWNBU0xDWGFxZndlK0x0
            RkxMWDlTVk1OTlp5M2pMNVFuU3E1TW8KNgSioluR9iZG+S5EEqRSM/4SZB9rmhES
            53qB0ueD+V4LyHsAk2lGmUZJ8lFl1EgABQPmxLSfeyYWw+B9e3rthA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-27T21:57:34Z"
    mac: ENC[AES256_GCM,data:WOe1gd5fBROmMgKtfoJuXFnF6sl0aKcErfGI3YCWZz+5h/F4b0Dbmj7F1otOODPsUB6YbI7rTvBIChObZiRMPO7VPiQjRXWBhjldJKqZqsDsOcXic+rPATH5ROYVDdscsoyX6QBo94ykCTntPiPB6F1dzVxnQ+JeqQEbXMzirP0=,iv:prkgPNxfi+znuCIS9vcTSXTynI5vWeDhvuHwV8vd+4c=,tag:qTOQbvM9kRqY5swPnDv/FQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
