---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./kube-vip/ks.yaml
  - ./local-path-provisioner/ks.yaml
  - ./metrics-server/ks.yaml
  - ./reloader/ks.yaml
  - ./intel-gpu-plugin/ks.yaml
  - ./nfs/ks.yaml
  - ./snapshot-controller/ks.yaml
