---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-home-assistant
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: 'true'
spec:
  dependsOn:
    - name: cluster-apps-mosquitto
    - name: cluster-apps-cloudnative-pg
    - name: cluster-apps-external-secrets-stores
    - name: cluster-apps-zigbee2mqtt
    - name: cluster-apps-kyverno
    - name: cluster-apps-longhorn
    - name: cluster-apps-ingress-nginx
#    - name: cluster-apps-volsync
  path: ./kubernetes/apps/home-automation/home-assistant/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-home-assistant-code
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: 'true'
spec:
  targetNamespace: home-automation
  commonMetadata:
    labels:
      app.kubernetes.io/name: &app home-assistant
  path: ./kubernetes/apps/home-automation/home-assistant/code
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
