---
## yaml-language-server: $schema=https://kubernetes-schemas.trux.dev/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app redis
  namespace: databases
spec:
  interval: 15m
  chart:
    spec:
      chart: redis
      version: 18.1.6
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    architecture: standalone
    auth:
      enabled: false
    master:
      persistence:
        enabled: false
#        existingClaim: redis-volume
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
