---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-volume
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn
