---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-volume
  namespace: databases
  labels:
    app.kubernetes.io/name: &name redis
    app.kubernetes.io/instance: *name
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn
  volumeName: redis-volume
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-volume
  namespace: databases
  labels:
    app.kubernetes.io/name: &name redis
    app.kubernetes.io/instance: *name
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: redis-volume
  storageClassName: longhorn
