---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age13hgue64xevk8x27umhxz7kyjectc52hrrx8p7kfyanlsmqsxjstskek2va
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age13hgue64xevk8x27umhxz7kyjectc52hrrx8p7kfyanlsmqsxjstskek2va
  - path_regex: terraform/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age13hgue64xevk8x27umhxz7kyjectc52hrrx8p7kfyanlsmqsxjstskek2va
  - path_regex: kubernetes/.*\.sops\.toml
    key_groups:
    - age:
        - age13hgue64xevk8x27umhxz7kyjectc52hrrx8p7kfyanlsmqsxjstskek2va
