---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app code-server
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    #controller:
    #  annotations:
    #    secret.reloader.stakater.com/reload: *app
    image:
      repository: ghcr.io/coder/code-server
      tag: 4.9.1
    service:
      main:
        ports:
          http:
            port: 8443
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "false"
          hajimari.io/enable: "true"
          hajimari.io/icon: code-array
          hajimari.io/group: development
          hajimari.io/appName: Code-Server
        hosts:
          - host: "code-server.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls: true
    persistence:
      config:
        enabled: true
