apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg
    namespace: databases
type: Opaque
stringData:
    POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:OVaEpWy1abs9msAF,iv:LieNSJKqLUXVzDzRubYJlPq0OivIBpMyc/zD884vgV0=,tag:zWQeDwWwwAydx9PNj2Gm8Q==,type:str]
    POSTGRES_SUPER_USER: ENC[AES256_GCM,data:w0ok,iv:AMFpWhdl4moFnjBvCymkW2sjM2Vcyse5l2eK862lrCM=,tag:V41bkYPproYl4dNmWS7R4A==,type:str]
    password: ENC[AES256_GCM,data:duVy+pb06YUVade0,iv:HodQ2PLu2bhodbxSIz2OGJNs5JLqO/onugEKp9pkrJw=,tag:kU2WNOA36ItUsERrOmufjQ==,type:str]
    username: ENC[AES256_GCM,data:Wqq8,iv:tepMfqi3R+XNBsz/4QktLOJuKW8Ukh+Kx1+hILyoWhs=,tag:hPwUYdNJrx9dNZXfKjDr4Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13hgue64xevk8x27umhxz7kyjectc52hrrx8p7kfyanlsmqsxjstskek2va
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZnZoY1h4bm4xdUp0VWJK
            Nk1HM3dHYnc5WmZNOVByRGhoSGNFblFyU0JBCkViSU9hQjRWNExqZzdQK0E1T0o3
            T2VWYTlkSFJOcDJRYlVzZVRjYnRncnMKLS0tIFNUaCs2WGFNcjVRcjJUMmNXZWhG
            TkJ1WUZFdDV6cXhYRDFlTGVGSjAwZjAK68/ZmPEjMzNK8HkFVFcNchx3Qdjgvoyo
            7aO2ZWkbIwNofTjQjo49/2TZEvloojPzr2b6wXxSnedUcaGQslo3JA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-26T02:38:09Z"
    mac: ENC[AES256_GCM,data:q8SQUTMYpTdpbiXKjn8xMO7n5NwSbtmEndcktNRYOuMmtdy2rXgAb4aJDa8pz0mCkWtY1d2X9qjuBp/aeTxSuy6AFP4Dpuhk1/TMoShnUvyFMriXyYiGbOkkDCTejSPttH3IyS2DzrkNqhc/OTpVYXKGEUsoVY0933ZxGNlAYAI=,iv:8Bhs3bBFX2WhYLSL57E+gni34ufs5cGUqIeMHPKTPLQ=,tag:MDwaaZwOoSd7Os659UQbaA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
