apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg
    namespace: databases
type: Opaque
stringData:
    POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:wcGALLUGpHMYAyaJ,iv:zPZx9MKf5K9on9lbdQkZKimLyd3NMQNbathbqSYYD20=,tag:LC/mk4dnSseRKU1btncXJA==,type:str]
    POSTGRES_SUPER_USER: ENC[AES256_GCM,data:elhHVWY6NjM=,iv:YrXh3EZxeK9yFrzB3hIvfnnivEMJETGeL470DxGuK5M=,tag:zUV8Lf9Ue5y5yXnQMMTiuQ==,type:str]
    password: ENC[AES256_GCM,data:XdpZmEI4sOqrb3IJ,iv:V8DOUyYcLE15FB0Ufs0aThP4xOCkkaXJEYG2VGP35u4=,tag:c+/B3aHlU/j9WhEfPWTthQ==,type:str]
    username: ENC[AES256_GCM,data:S9829oKe5NQ=,iv:eEm+oE2P85vy1Bid2o2lTzt5TXWqYHlqpU2wvRQ5Oyg=,tag:RHrLyb2h8GKLZZoIjsQFTg==,type:str]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:1QOQxMiC/QCglmUUIzk9yQ==,iv:/LuJQT37RR0Ty8Ey4Uson5tvTsnfQS8cy/TBbU9spuw=,tag:yZYn5gGkl1wqBlfvIB8kbA==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:xcYu6HD0ksJIxNEtEZNV99djzSsYuq6+klZ/7pcDXCI=,iv:dIuA3OAWHVXH9YMmDFs3v1Zz6mMCc1QMWQFzM7bkD/s=,tag:HsD9dqEKOFZ5Na/9dOxFlA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ve4vex7peq7guyjsdlsk3uvyujf7t9dq6njaac0cr079kcxan5zq22a0au
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRL0VLYUlVSTFubG5HQkc2
            K0ZnVTUrTGZmb3lhcE1TVFUxZEZ2aWk2Q21ZCmxyUFRtTlJSVkh3bFl0akxpVWVX
            VEVZUzNoVTV2VjZ0cnloQVk2UDdWMUEKLS0tIExBd2V6ZFo3aEhrYzhMb2Q4T2VO
            dnFOcnNaWlRvZ2NRRXNDcXR2VFNucWMKNf2F1y08oJSydmS3nE0ILDmXaSbrFsyf
            juN7bDftnQtW6L/zrPhEMTDtArpwcisAE9uTPZlot+GW0V0RySkawg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-19T19:34:43Z"
    mac: ENC[AES256_GCM,data:n3RQ5zrM3H3sEkgRkM0S+aUrNeadJs9wXqdx2aUr8sP+KvaGNV3/Q3wcRanbD/41TYGd6o2frBtFf9YJSHptgY/BqEe9usk8dK3LQiJQTvrId7sUOHnFTdi9vRTAHqXEQWhEbaHriY/1nSkq9X005bHziMdf9Su6bCntdwcWnQI=,iv:JHPhvXhEK+xOgpSq3LMItu1wCFuyB7PGOTRkWNdL7jM=,tag:0sVG1eljnvrd8OKPWq+KsA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
