kind: ENC[AES256_GCM,data:KYGtg4yp,iv:LKJ5iWNAkH6eHIaPxjFG6uqlYSQSIsAyWFlrdZdiPwA=,tag:361Jq7EB5vNq5ESb7h3EwA==,type:str]
ansible_user: ENC[AES256_GCM,data:K8yc,iv:v71an6nuNxfi0oUFbYiPdVEsWLEEj61L3ZWtbKrelv4=,tag:xWue6Hfw6RoGtngvyzkivg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:2cgiEmtzRo0=,iv:RfCV1LKOYUBCdzl30vB1g6g35eDfCaGSbNCg5ld7/1A=,tag:2vFn8AXyTfyxCpTCdkss/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13hgue64xevk8x27umhxz7kyjectc52hrrx8p7kfyanlsmqsxjstskek2va
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UnA3OVNZczdua3lqVzFX
            cWVjNkhRS00vRENwTWtiL1RXRkpiTWpCd0ZzCmM2YkJvTURDMnBtdUlkNXQ1bEF3
            NmZzbkdZQjRSRHdGSEVXM3BUbUMwak0KLS0tIDVuR2JpdFdCQ2hkbjVFbWZSZHll
            bnUwYWlJU2JRVzFPUDlOSExyeEQ1bXcKHXShSzLC3ezrLEMXFtnLYoB6TRvleZvm
            wPFvYpGFMM/27FAxG9DCpWKFITwLkJlPolT24g4oHZk01Tiq/euRRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-03T20:33:30Z"
    mac: ENC[AES256_GCM,data:tSf2AvtJiv/rBtYjt5LMaQaUugUSBAVs1BIiZTaA5PU9OXH3u9lAEnyzYlfI6AfCUjfxrIbpzfpx32Rr/yS8JDYbDUlGXmwjy7tesam0jMd2Vjf4UUZ8WrgYyWS0h1BfxwGCSpNkHkRfptzt5eZENAD+muDJ07o5ivSsAUpb0UQ=,iv:z+dqXagLTeL4SjrCfhf88skA51FABwkfOHqx6E5EszM=,tag:dmB/o2CKbPmdXygsShcGQw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
