kind: ENC[AES256_GCM,data:Fk++jJvR,iv:+DcslJ+UUWsjk1WUbPySnwhmrQ3Fy/5tGmcnpgf2j54=,tag:5nASQgIWc61AS7ql6NDhWA==,type:str]
ansible_user: ENC[AES256_GCM,data:Lmlw,iv:TOPNdC/13KIB8EAa7h0Z03eLg3p9NrzciX5QZFLCOlk=,tag:wxrX/bhCwbWvaDLxzl7FDw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:N9pxIC/4bTo=,iv:kRs+MXo1oGt5KZ/SnDylUTxUPI7xwDXFDoM8ZvWVsTw=,tag:Da3a8evy14+6LYhqLTXhyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13hgue64xevk8x27umhxz7kyjectc52hrrx8p7kfyanlsmqsxjstskek2va
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWEtPWW1UcHdLWDQrNGN3
            M3ZGQThSQUQxQWcyck1LdStrcUpKMVRhdTNVCnArazNUWHVCRCtZRmE1NDBBM2ox
            NEpCMHJZSS9BMWZFQXFKSDNSUCt6YVUKLS0tIDRaQVZJMGFRTEVlNHd3dWJOVFMr
            ZlJYZHV2SHpIa3lrdXpjaFVZMjNPQmMKjn75JQfVtZ1AoMMURrr+gdbN9CAny5ev
            6Jt9fFmB+ZYvbMn1+OCLslfNqkWK2Xe4A2ce20LTD8LG5OuudBvyUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-28T01:40:41Z"
    mac: ENC[AES256_GCM,data:+OTR5Y+XY6bJX/aSG6DaehF5XaEpyrx48HsDyFx4HMNa3ed3tdrOX7cR6Zx/J9ujXzkscZlHtEduQMxbqGLQ3wEZrSYNs3FM8bl7GEAYAy65iT3r3tH/eKp9hGC62a8M3cYGufxZWhXUBf2AjlBT343KKKsANDDqtJQvcn9VXck=,iv:cpJmUnm36FM1+yM1AuMHKMxYE48Dh+4HohkY9eHOi74=,tag:ZtAppr+3fRcGsfRuvmX72w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
