kind: ENC[AES256_GCM,data:WJAEPPxu,iv:3cdWLwUv8pv9bbo9H9t7QQx7VxTurKswW70etTITBzw=,tag:eMA1fI+G35fUiRD2oLobvA==,type:str]
ansible_user: ENC[AES256_GCM,data:13c9,iv:BebBhyV3jeMN8YIkjixSmxKYwJztF4kVScbeNHunxYA=,tag:cYRJc+qOcJZPHCrUcqs+ow==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:BU0jSjoQZmo=,iv:gTq6JngPdUb1fHH30BDUVCKIFImw9jR+++XtcMztM3M=,tag:Ni0mUNhYXocM/U0DOpFkGQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ve4vex7peq7guyjsdlsk3uvyujf7t9dq6njaac0cr079kcxan5zq22a0au
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpdUwxZ0xSUTVpUFRkS2Qv
            TXUvbnVDR25kbjNKSnpNcWtQTDZseU44Y1RjCm5qbmZSaTRUdUpXdzVHbndzVVph
            a2IvQTdUU0NTRUVObURMWkVwWFhiQVEKLS0tIGtlZmhJT3FjNzN6RXhjTDhuM0ht
            MUk5Q3BIanZTeElFYU1nMUl4VWlhREkKbrgMyVrfoupx16C3yhMUE5MU0eHuY7K9
            cfhpixXiMvhUTlU37s1mz4Wq5awtGhb4TkW70R84/B0lMgR7zXmZHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-17T14:05:28Z"
    mac: ENC[AES256_GCM,data:4iLm0oIXSEyeeTsEdTyVFNeUdrYnq0CaLXLEfGWniPJkRIaMGlkeH4+i+B4A05l1ddB0w4ZivMfgQ1vUulzefnAVhjO33vEtO6Fnm+Sy6VZnwsYjSLeDNfe/V1bzOZbOTLmvVS7LWGMemP/UfhdmyJ1WvMzvCIAWPQ3JDq9EpDU=,iv:F7hajMbT68bHIeuNvt/Y8spnldu8yRY64tC57KR4YZc=,tag:lRKDUS5oGM7faiG2aZJuQA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
