---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./cloudnative-pg.yaml
  - ./external-dns.yaml
  - ./external-secrets.yaml
  - ./hajimari.yaml
  - ./ingress-nginx.yaml
  - ./jetstack.yaml
  - ./k8s-gateway.yaml
  - ./kubernetes-dashboard.yaml
  - ./kyverno.yaml
  - ./metallb.yaml
  - ./metrics-server.yaml
  - ./nfs-subdir-external-provisioner.yaml
  - ./piraeus.yaml
  - ./stakater.yaml
#  - ./weave-gitops.yaml
  - ./longhorn.yaml
