---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-automation
resources:
  - ./pvc.yaml
  - ./sops.secret.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: mosquitto-configmap
    files:
      - mosquitto.conf=./config/mosquitto.conf
configurations:
  - ./patches/kustomizeconfig.yaml
labels:
  - pairs:
      app.kubernetes.io/name: mosquitto
      app.kubernetes.io/instance: mosquitto
