---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-config
  namespace: downloads
  labels:
    app.kubernetes.io/name: &name deemix
    app.kubernetes.io/instance: *name
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: longhorn
  volumeName: mosquitto-config
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mosquitto-config
  namespace: downloads
  labels:
    app.kubernetes.io/name: &name mosquitto
    app.kubernetes.io/instance: *name
spec:
  capacity:
    storage: 512Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: mosquitto-config
  storageClassName: longhorn
