apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-secret
    namespace: home-automation
    labels:
        app: mqtt
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:QBGO,iv:SgwkaHlYNpyiQfs+aFTixqAi+z3Ri/FUQg11ZXvFk78=,tag:bTp6UAy+8fio761eDgkKHQ==,type:str]
    password: ENC[AES256_GCM,data:9X0tXDSBaOvo8t6q00Ona+s8EUlEKE/er4V74ReOtDriStN90MRRBgsLuNzUdDN5+wnJ/DDrFHkBRweWoLwROF/4wjlZIMXh5CrAWoxi4UF1kypW+qfNs3FLM+WO5iKIBjqIKtjcSIRm7R/b,iv:mfFYi+tpF81TpnlJ/mCRzBWPJgUaaDiQcBy277K0JVc=,tag:xAAmFofLMcDm/BtFfCxQlw==,type:str]
    mosquitto_pwd: ENC[AES256_GCM,data:8Ly3mq+8BlHkOZIDP0xpA+9akAdwZiEoDaf+VtqKvCsxh6rQI1YYWaDkSVnDnqg1ZjvtQVwA+TO7zsES44p3V9Mnx82PWnl6tdOZC0syc8Tlu3oAIRN4V+ZwfDFOAitayhA9BhECxc62iwJ7+P6CHQ==,iv:VEYx3WjGPVvkXR/cAWDf/jjKnyenavgzk3nFt9vIf/A=,tag:E2nItPkwOdjRS1eJDYRpHg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13hgue64xevk8x27umhxz7kyjectc52hrrx8p7kfyanlsmqsxjstskek2va
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZ3RwanNpcGVhdWtKNmpq
            azliREdleFJsUjdaOUpxUllSTDJhRDJIdndnCkxGQ1oxNTRPdml2YlZwSksrZlRJ
            ZTE1ajc2OVRzSWxWcnEydDEzTjY5WEkKLS0tIDRNbEk2T2pRNkxSYTlHMDlzRVpi
            VzhGSGtobHRHTEcxTGZ6MzFrcWxqY3cKIGGNOerAIXO7DGaXxhmAjk5lLDyrFsrO
            OhQem6W2xuYB1xzIufw9VNxyjMBP0hCr+nhE5EU4bJt3BmTs1lYYxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-04T19:27:34Z"
    mac: ENC[AES256_GCM,data:EmeTkR0f617gXKkV7I3V+zDkGUt2fhvOo4Puw58dccwD8fjpxX7lh6iel/n/b7Vz9JOsQJ7rKa8io2LVqen4XfqMarzkt+HIyFtymkC9yC3e3vdTWuLdvXKwtP+cwKBKEqO6G//BAxDjJYTo0q2EveUpUPKi6j2ZCvd0dNjeiJ4=,iv:Q7H4YxusCb4Eu78C7sw3bLPFqkcwUve36GJ6mzQKm10=,tag:AylNzpufbtxXBDYnRnH73A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
