apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:+C34TSe4RdUBkKXPz88sIT8WN6iZXNnjnp30Tg94E/FaodnUL3gfEQ==,iv:k7QCPMi6+983a/QMt7UCda9dtMKX4e1JUf3edYeOV48=,tag:zjprcd6ke73KhC8F7QY7jw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ve4vex7peq7guyjsdlsk3uvyujf7t9dq6njaac0cr079kcxan5zq22a0au
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArb3NqSmlJYWFDVWR0L2Ro
            V0V6eXFaYU00SFdhRDd4MXhRVUJrZzFGZDNNCnl0VkwreDlocHJxNU5PR1hoL0FW
            QkVOeFhZejhZZWNtQXV2VFpMU091NkEKLS0tIDF0RnpOb3M5bmNPY2xJbUw0c0NW
            T3pXS2FZdU5tdnpsd21kaHJ0NTRaN0UKKYjx4YV7JjFQ4nH4YDtyNo8a/2bPrJ+y
            4oedE6zxBOJOMYsDqiSUjr1J9bl8hFPoTIQwC3fXaHvbmvohRRz4AA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-19T20:09:18Z"
    mac: ENC[AES256_GCM,data:52xSkJOhTMEq43jOLtayg37p6RrO2dtQ+5+jT0kwgrwkk8Z6CFgmLHSjp39S5nIJrzhAP5gGTZCbegUAErRorgwaiwuhaar/EYZXSZVeYVILrOTch8bqLDjGoCETNN0Vq10PZEkfmJTXE4m5TR4SZRaL/sBckYDRJWTMDGm1Rlo=,iv:Uo69vDFUgC9I8w6qUqMsxA6DdrF9UTFxRv383Jc2+mg=,tag:H1KnRETRIgqNBnu2BQwZlw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
