apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:I5xb16OuyN3KxG8IKUYD3iJ5YlAOhc822kXdnZyEgOSc4MTIaCSHgg==,iv:RGBku074+2zsy1lwxmIwPT3/PfSzrMp5h53xBkFyDms=,tag:RomSkUu1nBVJdQeh5zaURg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13hgue64xevk8x27umhxz7kyjectc52hrrx8p7kfyanlsmqsxjstskek2va
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaOG43SlpIZUVEVXJpQTdS
            UjFFekUwVWVPcnN1MWREZ0EyZitDc2xqMmhBCmR2NkdFVVJQVEZJMkMvOHExaHFB
            MTNpa2QvZUoyRnA3Zjk3VCtFRFpZbjQKLS0tIHpzUkZFTE1MYWRxVThlTWxIbFVJ
            blFYMGZGQnZwZHJwSkV6Nlc5dG5VYlkKl9m3M1WfzMbeaFLD93rlQWbBwPHodB+j
            ihJmFz+mXRVycUtfxOPSp/PblTP+qTXr9pBOjBGzLLwv/U5Kc6ub6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-03T20:45:03Z"
    mac: ENC[AES256_GCM,data:uoAHDBm3d8nvn81WvpoRMUWbaqUQuuYONwfTy82io9al1EamNJ4ZEHWnDw295eNDbN2HOH93iz1w0k6w7joRO2j7XoC1m57KsEr3fH6N0VS92KEvJtE2ySvGmd4ykYrOouodeKxYYntgzT7U/ynMsA/1TKjrC3uoJGfLnDM7Jaw=,iv:vILxY6nZYhQRxsazYIN6BIwcj7jiecGt0aa9AleU7JM=,tag:NukX/47yUQcnKEPGGUYVyA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
