apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:InPARINwX91Da6qqBnfbtDvsV/P+GUXxgrmDTiDBFKKNemaUeeseNg==,iv:KgeAXTpdHsMcl6tWbOVJUGQxYmLx6TO66jE8IlN6NSA=,tag:GgDa8zjVZ0Xa8cK5DA6OPA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13hgue64xevk8x27umhxz7kyjectc52hrrx8p7kfyanlsmqsxjstskek2va
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjSStCUWpOdUp4eFN4K3VC
            MDZNVjF4d28xRFpmS25sMHBsYVZpVTl2T1FVCncrYzdIUG5VMk02enBHRmJqdVVH
            VFRJWmlSUGtYd1J3ejhRSzNyUWZPc00KLS0tIHA3MGVqcFFKTE13NjMzcmJBQ3Ar
            MUdCeDJIM3p2Zlo3cGlUdURySm42SmMKSRZzldEqOMryejt9R+8BqtN7Nhm06Gm0
            pC8BrXaWSpQRf2+AX/yr9/1XLHfqbeYDsGCwjYh0GBGQF6O28kxPWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-03T20:33:30Z"
    mac: ENC[AES256_GCM,data:YpMPZOjohPj15dI316ntEb/2nIqmXolnsCXulSAYT0/deCL0bmsPSTE2Cwfoo7+AXiJchpUMNbzlhMxa9JgJTaWmuHjCt7qKeGaP2iU7tiXYt/1IBf2d30g0MP9mrjIVSeHlE1w0Lj3f8akHSzR4aOvEQD6r+Ax/FzPM3/aLRdE=,iv:4KXqNQmg3Zw127X1ex7MCiyroWh7CoPAGqd447fAV1I=,tag:AzlSEG9TKYUMfr2DeYOAyA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
