---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-config-v1
  namespace: databases
  labels:
    app.kubernetes.io/name: &name pgadmin
    app.kubernetes.io/instance: *name
#    snapshot.home.arpa/enabled: 'true'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  volumeName: pgadmin-config-v1
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pgadmin-config-v1
  namespace: databases
  labels:
    app.kubernetes.io/name: &name pgadmin
    app.kubernetes.io/instance: *name
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: pgadmin-config-v1
  storageClassName: longhorn
