---
# yaml-language-server: $schema=https://kubernetes-schemas.trux.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app zigbee2mqtt
  namespace: home-automation
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/koenkk/zigbee2mqtt
      tag: 1.33.0
    env:
      TZ: "${TIMEZONE}"
      ZIGBEE2MQTT_DATA: /data
      ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_DISCOVERY_TOPIC: homeassistant
      ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_LEGACY_ENTITY_ATTRIBUTES: "false"
      ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_LEGACY_TRIGGERS: "false"
      ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_STATUS_TOPIC: homeassistant/status
      ZIGBEE2MQTT_CONFIG_ADVANCED_LAST_SEEN: ISO_8601
      ZIGBEE2MQTT_CONFIG_ADVANCED_LEGACY_API: "false"
      ZIGBEE2MQTT_CONFIG_ADVANCED_LEGACY_AVAILABILITY_PAYLOAD: "false"
      ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_LEVEL: info # debug
      ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_OUTPUT: '["console"]'
      ZIGBEE2MQTT_CONFIG_AVAILABILITY_ACTIVE_TIMEOUT: 60
      ZIGBEE2MQTT_CONFIG_AVAILABILITY_PASSIVE_TIMEOUT: 2000
      ZIGBEE2MQTT_CONFIG_DEVICE_OPTIONS_LEGACY: "false"
      ZIGBEE2MQTT_CONFIG_DEVICE_OPTIONS_RETAIN: "true"
      ZIGBEE2MQTT_CONFIG_EXPERIMENTAL_NEW_API: "true"
      ZIGBEE2MQTT_CONFIG_FRONTEND_PORT: &port 8080
      ZIGBEE2MQTT_CONFIG_FRONTEND_URL: https://zigbee2mqtt.${SECRET_DOMAIN}
      ZIGBEE2MQTT_CONFIG_HOMEASSISTANT: "true"
      ZIGBEE2MQTT_CONFIG_MQTT_INCLUDE_DEVICE_INFORMATION: "true"
      ZIGBEE2MQTT_CONFIG_MQTT_KEEPALIVE: 60
      ZIGBEE2MQTT_CONFIG_MQTT_REJECT_UNAUTHORIZED: "false"
      ZIGBEE2MQTT_CONFIG_MQTT_SERVER: mqtt://mosquitto.home-automation.svc.cluster.local
      ZIGBEE2MQTT_CONFIG_MQTT_VERSION: 5
      # ZIGBEE2MQTT_CONFIG_MQTT_USER:
      #   valueFrom:
      #     secretKeyRef:
      #       name: mosquitto-secret
      #       key: username
      # ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD:
      #   valueFrom:
      #     secretKeyRef:
      #       name: mosquitto-secret
      #       key: password
      ZIGBEE2MQTT_CONFIG_PERMIT_JOIN: "false"
      ZIGBEE2MQTT_CONFIG_SERIAL_BAUDRATE: 115200
      ZIGBEE2MQTT_CONFIG_SERIAL_DISABLE_LED: "false"
      ZIGBEE2MQTT_CONFIG_SERIAL_PORT: tcp://192.168.1.171:6638
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/icon: mdi:access-point
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: zigbee2mqtt-config
        mountPath: "/data"
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 500Mi
