---
# yaml-language-server: $schema=https://kubernetes-schemas.trux.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app calibre
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/linuxserver/calibre
      tag: version-v6.14.1
    env:
      TZ: "${TIMEZONE}"
      PUID: "568"
      PGID: "1000"
    service:
      main:
        ports:
          http:
            port: 8080
      webserver:
        enabled: true
        ports:
          webserver:
            enabled: true
            port: 8081
            protocol: TCP
            targetPort: 8081
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        loadBalancerIP: "${SVC_CALIBRE_ADDR}"
        annotations:
          metallb.universe.tf/allow-shared-ip: *app
      wireless:
        enabled: true
        ports:
          wireless:
            enabled: true
            port: 9090
            protocol: TCP
            targetPort: 9090
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        loadBalancerIP: "${SVC_CALIBRE_ADDR}"
        annotations:
          metallb.universe.tf/allow-shared-ip: *app
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/icon: mdi:bookshelf
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: calibre-config
      media:
        enabled: true
        type: nfs
        server: ${NAS_ADDRESS}
        path: /volume1/NAS/Media
        mountPath: /media
    probes:
      startup:
        spec:
          initialDelaySeconds: 60
          failureThreshold: 160
