---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  releaseName: longhorn
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
      interval: 5m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 1
      reclaimPolicy: Retain
    defaultSettings:
      backupstorePollInterval: 300
      # backupTarget: nfs://${NAS_ADDRESS}:/volume1/Backup
      createDefaultDiskLabeledNodes: true
      defaultDataLocality: best-effort
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      concurrentAutomaticEngineUpgradePerNodeLimit: 1
      storageMinimalAvailablePercentage: 10
      defaultReplicaCount: 1
      defaultLonghornStaticStorageClass: longhorn
    ingress:
      enabled: true
      host: "longhorn.${SECRET_DOMAIN}"
      path: /
      tls: true
      # tlsSecret: longhorn-tls
      ingressClassName: nginx
      annotations:
#        kubernetes.io/ingress.class: "nginx"
        # cert-manager.io/cluster-issuer: "letsencrypt-production"
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        external-dns/is-public: "false"
        hajimari.io/enable: "true"
        hajimari.io/icon: cow
        hajimari.io/group: storage
        hajimari.io/appName: Longhorn
