apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:8tZFPiSwlIPiB+0g056Qp9764T6tqBKsKXuj/HZMa6HVztU6Lw==,iv:nfJyBA3yvuV9CQ+PY8tsSUturCVeHSx2ENb6Yu8pfiw=,tag:jS0OKDF5lHBizNdjuaAZDw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ve4vex7peq7guyjsdlsk3uvyujf7t9dq6njaac0cr079kcxan5zq22a0au
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndWEwVk9hVEZkRFc3QlY1
            OHdqdTdXMDZzYlJMVE9oQlJLQ0ZCN2pObkVFCjRHVis4NWtNUDgva3BQaVFuZXo5
            QXdGRWg5b3VWSEM4OWtsM3IxT0tKQ3cKLS0tIEtUN1UzWFlNMjNhUk80aEU2bXBv
            aEE1cVdrakZXSHlRU0xlVERVTnVMMkEKQd7YI/nLj+ssuqOw7TPRC0BZAJHzPNLa
            7huDdKY/Kslr61cM6su0AxQdg1fmCJEskwA5TOqQHbH+J94AAcQz4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-30T17:01:21Z"
    mac: ENC[AES256_GCM,data:AKyh+SXN/9icGbCXCTBeaoH8fYFd/bxuT+WbvL6ZheROf+q/J4o5TW85sr6+NrzMQmJDmSP1e/0RlycQxQa+zDc0SJLkIgl2g6zOhxN1RNpIKsJag3V0fMb4FFokY6LOKp8dmn9JiJ3ZPcrIV9+6pPilkb4Y7nl/uwk0A9LzWPA=,iv:QwWSJ/H13YswibUu3IytTVhpRkDZMBkRWTlU+u340WY=,tag:HAR6vbMFLz4P/RwO+o3fLg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
