apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:SodhNCmExruNeP6oPPSiw7qc58KQyPPWY5Mhd48eDBMIUCFVew==,iv:ByzZI1ysTRozh+hNXd/4WJxsA8EgbnZRj4UjFCjt4gE=,tag:XWNVuObzISk7gq6RaXvVjQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13hgue64xevk8x27umhxz7kyjectc52hrrx8p7kfyanlsmqsxjstskek2va
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTHdpTU1rNXYvM2JORXdz
            Z3BPN0g3YU02dzFoWXpGcDhRMnV0dmgyV2tnCnVubUFreEFhb3A5N1FmaVUzMngx
            Rmp2MFZPNm1DVTB1NlA0enNqaHlaTEkKLS0tIDdNREZzd2hrZk5OeHRUbjJrdjhK
            Zi8vTzJ2c1RtSnlqMjNueGFrbk9qaW8KpKcxCOZQRoYYfATqzqfkiOure7OOd4aE
            CXiPGaqYsTNR1z6dTTELW6gZZB8OdHhp/Nffsll/e0IBE6bdbeCrrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-31T14:34:29Z"
    mac: ENC[AES256_GCM,data:dy0j0COYIdGP1mdf+sZla32xjq8iku9fmNXZQbKQn3uQLvja6hqr0JwY8friMnzEq2dqW7AAaEVWc4ckwtbjfbY8qnt4cj6vuYPXKqmqjJAH/n/bl0jzF+IbuIdufbm4k1LBdy3GIG4P+F/CPhXRsd48DwWa2DVJKAhyrx/9HQ8=,iv:PJoTpjR1W+NpL0ERettZf7/bbP18zx97ynBnxiPJs1c=,tag:k19XHUSWdmO4S8EIoQihhQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
