apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:POhRtXyTkHiRM7grFe8qPl1N1ZFP2kImzs4VBp1M+0V/6pTvAw==,iv:9ZLFvpp/X9wt1QK+yH4IViCf+7aafaaGwFw5AVFU0CY=,tag:zUcvkAi/LTAYiO1T+zOEqw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13hgue64xevk8x27umhxz7kyjectc52hrrx8p7kfyanlsmqsxjstskek2va
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyOUMreU1nMWNxOHpvRitw
            K09yd0pYZ2FFZ3RWYVA3RERQeG8ybkdKSEdZCkh1ZjdkTGtPOGI4V0h5WFYzdTNh
            eXNxTHAwSXZHdHRHY2E4UDdCalFKOEkKLS0tIDR6VDRleVIyVWNuTEltZzZCVGdw
            NnZLczdkSk9BYlhLTHF0NzFTbTh1MDAKiK+6AtZGyuSiEHbJx8j2q52fX2hyEYi9
            yb8LdbS/U0uVFMZI+K3GLijmmMTXS/51mqq14JL6Wz5b16MMLdgM/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-27T21:57:34Z"
    mac: ENC[AES256_GCM,data:Eu8RQCIH4AWu+tAyj0fUvVRD7YrBiZ8MTfBFkgZ8wdqBRbEf7lXMm+p2/Uo+U2EpOBdAQbwcEIcKqfQp+BaxhPFU4IVovqKeviMLaE+6/4fvAkWR8IerYH8FaWfU+loVZb88Hwvz5DfvK06vWHXE8EUTZT8WTQckBKcYG/XWB3c=,iv:XOLWg3DaVGRN+PpyIsUXNgiTPXyt9IGW53d1S9RRt6M=,tag:+xKrus93WK9/5Wd43bim3A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
