apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:t71tmanYzI77mVOUdqSwWxt482HqIV/W5QfXNIh4qjgVsDTeSQ==,iv:9lWroUMhJYvjFACwH3Wo+y/sdh5ivMU7l5dkMTBo1bU=,tag:9oaLnlanDSLcNVfRf4gyXw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ve4vex7peq7guyjsdlsk3uvyujf7t9dq6njaac0cr079kcxan5zq22a0au
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMNXB5bzNQRUhTaHdXbFpQ
            YTRjdmJicFZteUc0dEo4YklqbmYxU1p1Z1dnCmxpTmtYYjNJa1MwM25NZ2I3UjU3
            aGpZYnBTaHk4akN2SHorWERTeW5acE0KLS0tIGxURDdsVFdTc0dSSWpjd24rWkpi
            VXBWMEhOUVpOazB2Q2JNQjY3aWpQZzgKdjrihOEr69x9kvZ3CKQdqf+ukkIHDXfn
            KfNcUteRh8WwJ//b4vu+bslyHkIWahsfBOW5Q+w/nbYL2X/oF6DLxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-15T11:39:03Z"
    mac: ENC[AES256_GCM,data:0mPgVgp1phURwZEHW3v0pzZf8D1sPQEnBg4wzq4x/FfTZRMMUXdul0uVYLweWHtcETYl8HuHTr3uuyf3jrfvJJkN4pQxAvIy91J78sYfzevOu4aF9UA+AYlkJOzkaaaWaxpgF2b/KoAZO7R3bZ9NZ1xDAVnjmi5WsecsGhlpAyo=,iv:uvYmE1MCAFvO3STuufFkwJ/Zvoqr6s9ToB2+hm8nYxI=,tag:zJj2cNdqkPxGe2wp1DXMpQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
