---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-configmap
  namespace: media
data:
  DB_PORT: "5432"
  IMMICH_MACHINE_LEARNING_URL: "false" # Disabled until future updates to Immich
  # IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning.default.svc.cluster.local:3003
  IMMICH_SERVER_URL: http://immich-server.media.svc.cluster.local:3001
  IMMICH_WEB_URL: http://immich-web.media.svc.cluster.local:3000
  LOG_LEVEL: verbose
  REDIS_HOSTNAME: redis-master-0.redis-headless.databases.svc.cluster.local
  TYPESENSE_DATA_DIR: /config
  TYPESENSE_HOST: immich-typesense.media.svc.cluster.local
