---
session:
  redis:
    host: redis-master-0.redis-headless.databases.svc.cluster.local
    port: 6379
  domain: ${SECRET_DOMAIN}
access_control:
  default_policy: deny
  rules:
#    - domain: ['auth.${SECRET_DOMAIN}']
#      policy: bypass
    - domain: ['*.${SECRET_DOMAIN}']
      policy: one_factor
  # identity_providers:
  #   oidc:
  #     cors:
  #       endpoints: ['authorization', 'token', 'revocation', 'introspection']
  #       allowed_origins_from_client_redirect_uris: true
