---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-config
  namespace: downloads
  labels:
    app.kubernetes.io/name: &name sabnzbd
    app.kubernetes.io/instance: *name
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  volumeName: sabnzbd-config
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: sabnzbd-config
  namespace: downloads
  labels:
    app.kubernetes.io/name: *name
    app.kubernetes.io/instance: *name
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: sabnzbd-config
  storageClassName: longhorn
