---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-config
  namespace: media
  labels:
    app.kubernetes.io/name: &name immich
    app.kubernetes.io/instance: *name
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  volumeName: immich-config
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: immich-config
  namespace: media
  labels:
    app.kubernetes.io/name: &name immich
    app.kubernetes.io/instance: *name
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: immich-config
  storageClassName: longhorn
