apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Up0FF+wV9A929XQ1,iv:7M0OrPonNv2njD6+h0dWM4eM6tR2G5qJHE/wOqaxW2I=,tag:zONFoMGTI279XNVE6EnVLQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:z8S/zjIM+91pqKl3YUbp4OM=,iv:HF8/kAZ+m4vbiIfX4ACHrBqtrtdTQ9G0lBEpTzTo5lA=,tag:xKp7ZHKvGLU1n9aDkLFPVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ve4vex7peq7guyjsdlsk3uvyujf7t9dq6njaac0cr079kcxan5zq22a0au
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQ1kxalBzQnU4L3NUbjdY
            MlZyaHNSc2JQZThlM0xTdFpVRUVZRnYyWUh3ClAyTFpKckpEdnhJSFQ2dDBOaEFq
            MmgzbkYxVmZRZVY2TWFUMkMxNUJPY3cKLS0tIEZncXBmWDk5bU5LQXJKOVlXeVBP
            T0ZQN0FacHVnTE1jSkNVblFuMEM5WGsKUqbYgwzSzpeJ/ihmAodBo7GHAKoAqELn
            QFSX+3NmkPk6OfvE/gD+mMmPlVBk+Ol5M1jPO5pARVOrPc8P7lpt8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-19T19:42:02Z"
    mac: ENC[AES256_GCM,data:R9e3t64gW9V66/RNTBRRTIHc4hLmAlYEL7iXlqcTf0oLEw4t3qERf+58OXuLfcGjwLfagZMjFFdXWZwYJXdU4bjxc7U3yTSeFJT8IWSf0vZTW8KFjI1WOSXLBGE4R0dnQGua+ljX3rbgEwpr/jFkobvcSXY7u3YIDmRIVymDXhs=,iv:QCOk+TBFmUwcfJM6FB8XwmvF3olQNmtY4gwic23XE+U=,tag:W793+uCOs79d8CkEEBc92g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
