apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:CXB7/vYJ9MqVCE2X,iv:cADYUkZYLFdL0TVESYMCxvH0KM6XlQ5tQrqJwZ2yXE4=,tag:f1gk4jwe/iXWsV+m0JCVdw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:hb8GKBP7jaRrzW7DdDy5cuE=,iv:y+PH7JymR8jSG4xxq5HvINomwJofyUXgT7S/avWFOrM=,tag:zbIsoEDHHOn+JLQdFbvs/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13hgue64xevk8x27umhxz7kyjectc52hrrx8p7kfyanlsmqsxjstskek2va
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5TVdjVFlXZGw2VURJN1hS
            QUI3NzRXeXBSUmRabUJubFBYNk8vSkhjTXkwCitUTmVBUzFEaExrY0FQenhpeC9s
            c1ZHK2o1MUhiU1RHRjRDQUhmRTdpRjQKLS0tIFNHNXQ1cnZickN5ZmFrQmxZVjF2
            VnBXWjJBV2Z2SVZ3ZzJNVTBMQmVaUk0Kz8+6vzPxj7opbTtLD3L9bTfBIeoL9L55
            Es15V27+NdmLJiRfrcbrBKFm5tiVS+rmQR0p+lwrCj4a/2byS0qjEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-18T20:10:08Z"
    mac: ENC[AES256_GCM,data:OMasLHe2uLvomJ6POPCIvzKCEvaeDBvF+wpjiKwb7qqaXw//v4M6/EX5lY8rq1G+yffCuajF/DxkMksMXXIljsSR+hfLxtE9eOMv4NuHQMqg+5c/7a/VK5LZ1elWKlLL3JI//JYZ7SrhIE8SptiX7SqVw+6sW89aiYZVvUI7EB8=,iv:Wo5VR2khj/DYva/xWh4uAWa1+uWKuXbtDwDX/32jlgc=,tag:dsWNYsWNVvDi8vaQgpn8/w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
