---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentication
resources:
  - ./sops.authelia_variables.yaml
  # - ./servicemonitor.yaml
  - ./helmrelease.yaml
  # - ./prometheusrule.yaml
patchesStrategicMerge:
  - ./patches/env.yaml
configMapGenerator:
  - name: authelia
    files:
      - config/configuration.yml
generatorOptions:
  disableNameSuffixHash: true
metadata:
  namespace: authentication
