---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-automation
resources:
  - ./sops.homeassistant_variables.yaml
  - ./pvc.yaml
  - ./helmrelease.yaml
patchesStrategicMerge:
  - ./patches/addons.yaml
