{
	"data": "ENC[AES256_GCM,data:VxmMoksyG+TO2smUnAY1ynPcoRHQ+iETCKxyUaQy1lIF3OiTh7rOJFDUlQENgFuoXJJjBXSOoml3sLwDrLXBFS9lqoff4Vl9afniBgGxkFA3GypOYxSNd8Yc1B+KLwxkosqNUJByDSM6Z3g6P91FF6rqn+vi01/dLOI1VOj/c4IeJPz5/91jATGjlbV7CYvREJr8YsE9ia8A9JKwE98lXEA6V6F7iGxzPntYAEYthF15ll7+B5iqam9tr0gXOHmP4gkyVcVqr4WyCOf30JpYuCJR6NgeAJyjHM67TPYcAdqilrYNTw==,iv:Wa6UCjFvdqnsEtUZX/4Jyeba3PXcwwhoFnkuXEe9sPk=,tag:jSODqzPgHzJivLOIv/Cd5Q==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": [
			{
				"recipient": "age13hgue64xevk8x27umhxz7kyjectc52hrrx8p7kfyanlsmqsxjstskek2va",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWExlWkgyd2xaQU54WEND\nSVhxRDhWSTdReXNlRDhrZDI1cjQ2OStxZldzCnZ5MUJQdW91aFMrR3czeGlIWHdG\nRXl1RDBNQzg2Vnl2ckVoVHhnYnpjYm8KLS0tIGhLbVVZL1ZyemFKVUFlbkdKOWgv\nVkxDbmRWSkYzTzlrVExaSUwrMHg1blUKyntmiZmyM8Lw0VP4gTNrSbsv1NDU16/3\nAjbWtTpkXVNbzLVGixqM3VfbDI6XSvKh0CWWlDgwXqrBHPF7XXEUaA==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2023-02-10T19:05:54Z",
		"mac": "ENC[AES256_GCM,data:Yy8LsnV6j8TDG39Zkq8SUXMnrFKNB4vQjMYGb6MAalngZGuVoZcwf+nJTlGsYewMwAZogmkB+SDNmrNdZQSynUa+yQDpo8k5Psdr18F0mvIT5Lo0WmHPH/UP2bFRFs5iJz07L1Xe/BJ2kLgIbNAhVywNE3FPi3bxlUs6HAXs0eA=,iv:0mQJJwMkzynljCrS7mHmkYKExqrZ64GOFNgcZMrjwWY=,tag:9tErnz7ERfgv+X0njZWYiQ==,type:str]",
		"pgp": null,
		"unencrypted_suffix": "_unencrypted",
		"version": "3.7.3"
	}
}