{
	"data": "ENC[AES256_GCM,data:Ep48OfNI7UDJa5scWuqHkm9XGqcYBP0zO5acxqOK8Fj3+lcRzMmGrEI/pjjhONFPiFY1jFcOam6l9luFthM40bjxbQc2kamjCG3v+mGWHP4E32ZbJJRdReaq5Dv6+POJEBF01K9o6OIaOFhEp9H+q9yFL0wD9ayTd4jL/BUGp+fElOF1E/uzETnDzWauWXWgRBswoUqj0N8YPdG8YuPglDbMGad7fuTxp8K2EZB8Aw/XaGfIzoyixALIoKoMFM0WnBEidcgafMu2yXQptFvLbAFdibOmSzCaIYzk+MtgXNoQsjzJYqr8BQ2Pnq1ixZ3SMQvmpAHJ1e6HFRF3rjCkiZ9XyKyYyPT78YDVzdem2iOrnX36xavMKHd/Rxqw7OrPYKscfRw/5xnTmkUJcUb0TvPrfFfeRsNk8Qc9hti2fd9AJagpFrdjJl9PkU1QYtrrPr/oCap3vw9C5j4f5YGaZAXsQp56lOYBq4Q2kKdCOWNLwM456mLlRooBRBHX9g0tDiMIRblNwIKa4bz8Nf31Luri+8/ujxtLWR0wEV8BElbXYPVyzMdeDZmBj7y/P+Zkk2wcgnJs5H15TmaV3chKMJCGWGcSuvswwdkXhFUojZpwzzl/CggkB4MNgnCNXdfypV5Xo4uKPVC1M/q96Gbsxe6T/SN9YzcD87r0WoHyRwQq6jozuu2/82fHdYV02pStq4aen0kRmMOQ6lwDs/a5+kDRtnu13LY2yPVzQxgGP5pCdoDZ9CBQU+lFRotBJ61hoqznttAyHOxubPtvBU/+xJ4QyrDqL4YYgNMQW7yGFG7irOUxAFMSvRYH0d7kHXZVeq17efYhsioek1ksGp/pqmZZTXKYxMJnJMwSOaRiDEXdtYswPJIXAaTHc/n+1hDMiwK+Ektb8fEBg+Jk+v10DIgg4IgYsaKRFEy2b5A=,iv:KYMU5p5F/58rNkicvNx2TIoQTLpPJyMJPz/AFy5x3xU=,tag:n1OETGXzFlfKw1Sx1tzJhA==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": [
			{
				"recipient": "age13hgue64xevk8x27umhxz7kyjectc52hrrx8p7kfyanlsmqsxjstskek2va",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5MjdveEJFWThmSHA5RHEy\nT0JQWUJzS2NpT0Y3L1l1VVlIbVViRnl6SUJJCnIxcnRPSlBpOUpUNkdWNHN5bDU0\neVFVK1JZRWszL2RhdHlBUnJyWlRJbEUKLS0tIFV6dkl3SHhRSXFoWHcxb0w4MVdB\nT1RzV1dpeFY5NEZXWlNBV0ozZXdpRU0K7TUy+CKXyEDskoxEdOCEwQhUTUrIa4SX\no+AR8v28u0Pw0UGBMkPpkGZ5e4JlKORwv+FH+FFZ5DYGHXhblOroaA==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2023-02-27T19:41:43Z",
		"mac": "ENC[AES256_GCM,data:UCfc7zolIQaSynfSPeW2hvC8PkGOOQXJUkjmFRpglMSbwNT/uxCpOqectHJ1niWkv4x3bxFmTu8QZfm9ww6sszWsCR06Q9QX9U4cQ6Yjx7RUgPL8RJsKz1kUw94HpPUw8X3GaZUQwMnIp/a8SZ79XOVpnX3IHMwC1KXZpOY05LI=,iv:KOL1mwPiP4Ibk1H0waxnQipXsrVh90EfIJiqZyoHRbY=,tag:Hn3dL16wQ+YA9nz+XlFM+Q==,type:str]",
		"pgp": null,
		"unencrypted_suffix": "_unencrypted",
		"version": "3.7.3"
	}
}