---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: databases
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: "192.168.1.205"
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    postgresql: postgres
    role: primary
